apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: default
spec:
  replicas: 2  # You can scale this as needed
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: 575108922676.dkr.ecr.us-west-1.amazonaws.com/appointment-service-repo:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
