apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: 575108922676.dkr.ecr.us-west-1.amazonaws.com/patient-service-repo:latest
        ports:
        - containerPort: 3000  
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
