name: Kubernetes Deploy

on:
 workflow_dispatch:
#  push:
#    branches:
#      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up EKS kubeconfig
        run: aws eks --region us-west-1 update-kubeconfig --name my-eks-cluster

      - name: Apply Kubernetes Manifests
        run: |
            kubectl apply -f k8s/
          # kubectl apply -f k8s/patient-service-deployment.yaml
          # kubectl apply -f k8s/appointment-service-deployment.yaml
          # kubectl apply -f k8s/patient-service-service.yaml
          # kubectl apply -f k8s/appointment-service-service.yaml
          # kubectl apply -f k8s/app-ingress.yaml
