name: Destoy terraform infra

on:
 workflow_dispatch:
jobs:
  destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/environment/dev
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6
    - name: Terraform Init (Configure Backend)
      run: terraform init
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
 
